server:
  port: 9090

link-shortener:
  short-link-length: 8
  logging.enable-log-execution-time: true

spring:
  application:
    name: link-shortener
  datasource:
    url: jdbc:postgresql://localhost:5433/linkshortener
    username: app
    password: password
    hikari:
      schema: link_shortener
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate